// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: points_contract.proto
// </auto-generated>
// Original file comments:
// the version of the language, use proto3 for contracts
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace Points.Contracts.Point {

  #region Events
  public partial class ServicesEarningRulesChanged : aelf::IEvent<ServicesEarningRulesChanged>
  {
    public global::System.Collections.Generic.IEnumerable<ServicesEarningRulesChanged> GetIndexed()
    {
      return new List<ServicesEarningRulesChanged>
      {
      };
    }

    public ServicesEarningRulesChanged GetNonIndexed()
    {
      return new ServicesEarningRulesChanged
      {
        Service = Service,
        ServicesEarningRules = ServicesEarningRules,
      };
    }
  }

  public partial class PointCreated : aelf::IEvent<PointCreated>
  {
    public global::System.Collections.Generic.IEnumerable<PointCreated> GetIndexed()
    {
      return new List<PointCreated>
      {
      };
    }

    public PointCreated GetNonIndexed()
    {
      return new PointCreated
      {
        TokenName = TokenName,
        Decimals = Decimals,
      };
    }
  }

  public partial class InviterApplyed : aelf::IEvent<InviterApplyed>
  {
    public global::System.Collections.Generic.IEnumerable<InviterApplyed> GetIndexed()
    {
      return new List<InviterApplyed>
      {
      };
    }

    public InviterApplyed GetNonIndexed()
    {
      return new InviterApplyed
      {
        Domain = Domain,
        Service = Service,
        Invitee = Invitee,
        Inviter = Inviter,
      };
    }
  }

  public partial class PointsRecorded : aelf::IEvent<PointsRecorded>
  {
    public global::System.Collections.Generic.IEnumerable<PointsRecorded> GetIndexed()
    {
      return new List<PointsRecorded>
      {
      };
    }

    public PointsRecorded GetNonIndexed()
    {
      return new PointsRecorded
      {
        PointsRecordList = PointsRecordList,
      };
    }
  }

  #endregion
  public static partial class PointsContractContainer
  {
    static readonly string __ServiceName = "PointsContract";

    #region Marshallers
    static readonly aelf::Marshaller<global::Points.Contracts.Point.InitializeInput> __Marshaller_InitializeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Points.Contracts.Point.InitializeInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Address> __Marshaller_aelf_Address = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Address.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Points.Contracts.Point.CreatePointInput> __Marshaller_CreatePointInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Points.Contracts.Point.CreatePointInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Points.Contracts.Point.RecordRegistrationInput> __Marshaller_RecordRegistrationInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Points.Contracts.Point.RecordRegistrationInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Points.Contracts.Point.ApplyToOperatorInput> __Marshaller_ApplyToOperatorInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Points.Contracts.Point.ApplyToOperatorInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Points.Contracts.Point.PointsSettlementInput> __Marshaller_PointsSettlementInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Points.Contracts.Point.PointsSettlementInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Int32Value> __Marshaller_google_protobuf_Int32Value = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Int32Value.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Points.Contracts.Point.SetReservedDomainListInput> __Marshaller_SetReservedDomainListInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Points.Contracts.Point.SetReservedDomainListInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Points.Contracts.Point.GetReservedDomainListOutput> __Marshaller_GetReservedDomainListOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Points.Contracts.Point.GetReservedDomainListOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Points.Contracts.Point.SetServicesEarningRulesInput> __Marshaller_SetServicesEarningRulesInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Points.Contracts.Point.SetServicesEarningRulesInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Points.Contracts.Point.GetServicesEarningRulesInput> __Marshaller_GetServicesEarningRulesInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Points.Contracts.Point.GetServicesEarningRulesInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Points.Contracts.Point.GetServicesEarningRulesOutput> __Marshaller_GetServicesEarningRulesOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Points.Contracts.Point.GetServicesEarningRulesOutput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Points.Contracts.Point.SetServiceApplyActionLimitInput> __Marshaller_SetServiceApplyActionLimitInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Points.Contracts.Point.SetServiceApplyActionLimitInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Points.Contracts.Point.GetServiceApplyActionLimitInput> __Marshaller_GetServiceApplyActionLimitInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Points.Contracts.Point.GetServiceApplyActionLimitInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Points.Contracts.Point.GetServiceApplyActionLimitOutput> __Marshaller_GetServiceApplyActionLimitOutput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Points.Contracts.Point.GetServiceApplyActionLimitOutput.Parser.ParseFrom);
    #endregion

    #region Methods
    static readonly aelf::Method<global::Points.Contracts.Point.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Initialize = new aelf::Method<global::Points.Contracts.Point.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Initialize",
        __Marshaller_InitializeInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetAdmin = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetAdmin",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address> __Method_GetAdmin = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAdmin",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::Points.Contracts.Point.CreatePointInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_CreatePoint = new aelf::Method<global::Points.Contracts.Point.CreatePointInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "CreatePoint",
        __Marshaller_CreatePointInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Points.Contracts.Point.RecordRegistrationInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RecordRegistration = new aelf::Method<global::Points.Contracts.Point.RecordRegistrationInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RecordRegistration",
        __Marshaller_RecordRegistrationInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Points.Contracts.Point.ApplyToOperatorInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ApplyToOperator = new aelf::Method<global::Points.Contracts.Point.ApplyToOperatorInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ApplyToOperator",
        __Marshaller_ApplyToOperatorInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Points.Contracts.Point.PointsSettlementInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_PointsSettlement = new aelf::Method<global::Points.Contracts.Point.PointsSettlementInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "PointsSettlement",
        __Marshaller_PointsSettlementInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetMaxRecordListCount = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetMaxRecordListCount",
        __Marshaller_google_protobuf_Int32Value,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetMaxApplyCount = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetMaxApplyCount",
        __Marshaller_google_protobuf_Int32Value,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Points.Contracts.Point.SetReservedDomainListInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetReservedDomainList = new aelf::Method<global::Points.Contracts.Point.SetReservedDomainListInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetReservedDomainList",
        __Marshaller_SetReservedDomainListInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Points.Contracts.Point.GetReservedDomainListOutput> __Method_GetReservedDomainList = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Points.Contracts.Point.GetReservedDomainListOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetReservedDomainList",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_GetReservedDomainListOutput);

    static readonly aelf::Method<global::Points.Contracts.Point.SetServicesEarningRulesInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetServicesEarningRules = new aelf::Method<global::Points.Contracts.Point.SetServicesEarningRulesInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetServicesEarningRules",
        __Marshaller_SetServicesEarningRulesInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Points.Contracts.Point.GetServicesEarningRulesInput, global::Points.Contracts.Point.GetServicesEarningRulesOutput> __Method_GetServicesEarningRules = new aelf::Method<global::Points.Contracts.Point.GetServicesEarningRulesInput, global::Points.Contracts.Point.GetServicesEarningRulesOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetServicesEarningRules",
        __Marshaller_GetServicesEarningRulesInput,
        __Marshaller_GetServicesEarningRulesOutput);

    static readonly aelf::Method<global::Points.Contracts.Point.SetServiceApplyActionLimitInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetServiceApplyActionLimit = new aelf::Method<global::Points.Contracts.Point.SetServiceApplyActionLimitInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetServiceApplyActionLimit",
        __Marshaller_SetServiceApplyActionLimitInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Points.Contracts.Point.GetServiceApplyActionLimitInput, global::Points.Contracts.Point.GetServiceApplyActionLimitOutput> __Method_GetServiceApplyActionLimit = new aelf::Method<global::Points.Contracts.Point.GetServiceApplyActionLimitInput, global::Points.Contracts.Point.GetServiceApplyActionLimitOutput>(
        aelf::MethodType.View,
        __ServiceName,
        "GetServiceApplyActionLimit",
        __Marshaller_GetServiceApplyActionLimitInput,
        __Marshaller_GetServiceApplyActionLimitOutput);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int32Value> __Method_GetMaxRecordListCount = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int32Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetMaxRecordListCount",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int32Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int32Value> __Method_GetMaxApplyCount = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int32Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetMaxApplyCount",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int32Value);

    #endregion

    #region Descriptors
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Points.Contracts.Point.PointsContractReflection.Descriptor.Services[0]; }
    }

    public static global::System.Collections.Generic.IReadOnlyList<global::Google.Protobuf.Reflection.ServiceDescriptor> Descriptors
    {
      get
      {
        return new global::System.Collections.Generic.List<global::Google.Protobuf.Reflection.ServiceDescriptor>()
        {
          global::AElf.Standards.ACS12.Acs12Reflection.Descriptor.Services[0],
          global::Points.Contracts.Point.PointsContractReflection.Descriptor.Services[0],
        };
      }
    }
    #endregion

    /// <summary>Base class for the contract of PointsContract</summary>
    // public abstract partial class PointsContractBase : AElf.Sdk.CSharp.CSharpSmartContract<Points.Contracts.Point.PointsContractState>
    // {
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty Initialize(global::Points.Contracts.Point.InitializeInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty SetAdmin(global::AElf.Types.Address input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::AElf.Types.Address GetAdmin(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty CreatePoint(global::Points.Contracts.Point.CreatePointInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty RecordRegistration(global::Points.Contracts.Point.RecordRegistrationInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty ApplyToOperator(global::Points.Contracts.Point.ApplyToOperatorInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty PointsSettlement(global::Points.Contracts.Point.PointsSettlementInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty SetMaxRecordListCount(global::Google.Protobuf.WellKnownTypes.Int32Value input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty SetMaxApplyCount(global::Google.Protobuf.WellKnownTypes.Int32Value input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty SetReservedDomainList(global::Points.Contracts.Point.SetReservedDomainListInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Points.Contracts.Point.GetReservedDomainListOutput GetReservedDomainList(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty SetServicesEarningRules(global::Points.Contracts.Point.SetServicesEarningRulesInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Points.Contracts.Point.GetServicesEarningRulesOutput GetServicesEarningRules(global::Points.Contracts.Point.GetServicesEarningRulesInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty SetServiceApplyActionLimit(global::Points.Contracts.Point.SetServiceApplyActionLimitInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Points.Contracts.Point.GetServiceApplyActionLimitOutput GetServiceApplyActionLimit(global::Points.Contracts.Point.GetServiceApplyActionLimitInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Int32Value GetMaxRecordListCount(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Int32Value GetMaxApplyCount(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    // }
    //
    // public static aelf::ServerServiceDefinition BindService(PointsContractBase serviceImpl)
    // {
    //   return aelf::ServerServiceDefinition.CreateBuilder()
    //       .AddDescriptors(Descriptors)
    //       .AddMethod(__Method_Initialize, serviceImpl.Initialize)
    //       .AddMethod(__Method_SetAdmin, serviceImpl.SetAdmin)
    //       .AddMethod(__Method_GetAdmin, serviceImpl.GetAdmin)
    //       .AddMethod(__Method_CreatePoint, serviceImpl.CreatePoint)
    //       .AddMethod(__Method_RecordRegistration, serviceImpl.RecordRegistration)
    //       .AddMethod(__Method_ApplyToOperator, serviceImpl.ApplyToOperator)
    //       .AddMethod(__Method_PointsSettlement, serviceImpl.PointsSettlement)
    //       .AddMethod(__Method_SetMaxRecordListCount, serviceImpl.SetMaxRecordListCount)
    //       .AddMethod(__Method_SetMaxApplyCount, serviceImpl.SetMaxApplyCount)
    //       .AddMethod(__Method_SetReservedDomainList, serviceImpl.SetReservedDomainList)
    //       .AddMethod(__Method_GetReservedDomainList, serviceImpl.GetReservedDomainList)
    //       .AddMethod(__Method_SetServicesEarningRules, serviceImpl.SetServicesEarningRules)
    //       .AddMethod(__Method_GetServicesEarningRules, serviceImpl.GetServicesEarningRules)
    //       .AddMethod(__Method_SetServiceApplyActionLimit, serviceImpl.SetServiceApplyActionLimit)
    //       .AddMethod(__Method_GetServiceApplyActionLimit, serviceImpl.GetServiceApplyActionLimit)
    //       .AddMethod(__Method_GetMaxRecordListCount, serviceImpl.GetMaxRecordListCount)
    //       .AddMethod(__Method_GetMaxApplyCount, serviceImpl.GetMaxApplyCount).Build();
    // }

  }
}
#endregion

